plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.admobtestapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.admobtestapp'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:24.5.0'
}
